name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build
      run: mvn clean package

    - name: Trigger Jenkins
      run: |
        curl -X POST "http://<your-ip>:8081/job/deploy-to-tomcat/build?token=build123"
